title: Dokkan Entropy Wiki
description: >- # this means to ignore newlines until "baseurl:"
  A wiki to consolidate all the information regarding modifing Dokkan Entropy
remote_theme: just-the-docs/just-the-docs